### ISSUE TITLE
Alert message of Alert! something went wrong. could not generate simple-report!

### ISSUE THREAD

**Issue by shuxingcheng** [nasa-jpl/T-ENTacle#42]
I finished training the first document, 

python knowledge_facilitator.py --i --a --e entity_name.txt C:\Users\ugwz\Desktop\JPL\NOJV\new-use-case\Abraxas\test1.pdf

The following alert message was generated, 

![image](https://user-images.githubusercontent.com/40361065/48155263-3c526180-e290-11e8-8535-967227074a9a.png)

**Comment by asitang** [comment]
Hi Shuxing,
We added better error messages: please try again, so we know what is going wrong.
https://github.com/nasa-jpl/T-ENTacle/commit/4162bba8a1a12528f5e23ee81cdcf9e1b492fd16

**Comment by shuxingcheng** [comment]
Hi Asitang, 

I just downloaded the latest version using git clone.  It seems that the new version still has the model saving problem.


**Please enter the indices, separated by spaces, of all of the patterns you wish to select.
Or enter s to skip this entity or v to search by value.
s
Saving model...
Model saved.
Traceback (most recent call last):
  File "C:\Users\ugwz\T-ENTacle\text-analysis\KE_interface.py", line 234, in single_doc_cli
    self.knowledge_extractor.make_simple_report()
  File "C:\Users\ugwz\T-ENTacle\text-analysis\KE_class.py", line 738, in make_simple_report
    df.to_csv(self.simple_report_path)
  File "C:\Users\ugwz\AppData\Local\Continuum\anaconda3\envs\jpl\lib\site-packages\pandas\core\frame.py", line 1524, in to_csv
    formatter.save()
  File "C:\Users\ugwz\AppData\Local\Continuum\anaconda3\envs\jpl\lib\site-packages\pandas\io\formats\format.py", line 1637, in save
    compression=self.compression)
  File "C:\Users\ugwz\AppData\Local\Continuum\anaconda3\envs\jpl\lib\site-packages\pandas\io\common.py", line 390, in _get_handle
    f = open(path_or_buf, mode, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ugwz\\T-ENTacle\\text-analysis\\reports\\report_simple.csv'
Alert! something went wrong. could not generate simple-report! None**

**Comment by cosmoshsv** [comment]
Hi @shuxingcheng  , please pull the latest changes to test, or you could revert with the logs.

**Comment by shuxingcheng** [comment]
The training process can go through, without considering the result.

![capture](https://user-images.githubusercontent.com/40361065/48718283-af3cd000-ebe0-11e8-9cd3-05a657b148dd.PNG)
