### ISSUE TITLE
the option of v does not work

### ISSUE THREAD

**Issue by shuxingcheng** [nasa-jpl/T-ENTacle#43]
When I use v option for search, it seems failed.  By the way, can we use the phrase to search?

![image](https://user-images.githubusercontent.com/40361065/48158131-4cba0a80-e297-11e8-9fe6-6793fe66df23.png)

![image](https://user-images.githubusercontent.com/40361065/48158142-56437280-e297-11e8-8af1-993bf4eaf980.png)

**Comment by asitang** [comment]
Hi Shuxing. It only searches a value or variable like time, date, float, int etc but will accept anything. There was also a bug, that I fixed. Try again. A phrase will not work as it is not intended to search for phrases.
https://github.com/nasa-jpl/T-ENTacle/commit/3de1004d6d4a21c600548329ca0fc23b2505dadb

**Comment by shuxingcheng** [comment]
I tested it, the issue is solved. I am attaching the experiment screenshot for reference purposes.

![capture](https://user-images.githubusercontent.com/40361065/48717795-b6afa980-ebdf-11e8-92cb-52d8a6789c80.PNG)
